Repository 1-Platform/op-components, pull requests merged in 2020-12, with the labels that each got.

#156 fix(#155) - Current-step-index not working in angular in opc-timeline
  packages/opc-timeline/README.md
  packages/opc-timeline/package-lock.json
  packages/opc-timeline/package.json
Labels: bug, documentation

#164 fix(#163) - Op-Component Library generator is failing due to the webpack upgrade
  generator/generator-opc-generator/generators/app/templates/package.json
  generator/generator-opc-generator/generators/app/templates/webpack.config.js
Labels: bug

#166 fix(#165) - Change components package.json from webpack-dev-server to webpack-serve
  packages/opc-back-to-top/package.json
  packages/opc-back-to-top/webpack.config.js
  packages/opc-footer/package.json
  packages/opc-footer/webpack.config.js
  packages/opc-header/package.json
  packages/opc-header/webpack.config.js
  packages/opc-timeline/package.json
  packages/opc-timeline/webpack.config.js
Labels: chore

#132 Added opc-input-chip component.
  packages/opc-input-chip/.npmignore
  packages/opc-input-chip/LICENSE
  packages/opc-input-chip/README.md
  packages/opc-input-chip/declaration.d.ts
  packages/opc-input-chip/demo/index.html
  packages/opc-input-chip/jest.config.js
  packages/opc-input-chip/package-lock.json
  packages/opc-input-chip/package.json
  packages/opc-input-chip/src/opc-input-chip.scss
  packages/opc-input-chip/src/opc-input-chip.ts
  packages/opc-input-chip/test/opc-input-chip.test.ts
  packages/opc-input-chip/tsconfig.json
  packages/opc-input-chip/webpack.config.js
Labels: chore
