Repository 1-Platform/op-components, pull requests merged in 2020-09, with the labels that each got.

#33 fix(#30) - Create new command and add packages to root package.json and few other fixes
  README.md
  generator/generator-opc-generator/generators/app/templates/demo/index.html
  generator/generator-opc-generator/generators/app/templates/package.json
  generator/generator-opc-generator/generators/app/templates/src/_style.scss
  generator/generator-opc-generator/generators/app/templates/tsconfig.json
  package-lock.json
  package.json
Labels: bug, chore, dependencies, documentation, enhancement

#51 chore(#50): Setup Code Scanning and LGTM Shield
  .github/workflows/codeql-analysis.yml
  README.md
Labels: chore

#53 fix(lgtm): fixes LGTM alerts
  packages/opc-header/demo/index.html
  packages/opc-header/src/opc-header.ts
Labels: chore

#55 fix(#54) - Bump up opc-header version to publish on npm
  packages/opc-header/package-lock.json
  packages/opc-header/package.json
Labels: chore

#57 fix(#56) - Add usage guide in Generator README
  generator/generator-opc-generator/generators/app/templates/README.md
Labels: chore

#68 Replaces SVG Background images with data images
  packages/opc-footer/package.json
  packages/opc-footer/src/images/left-footer-cubes.svg
  packages/opc-footer/src/images/right-footer-cubes.svg
  packages/opc-footer/src/opc-footer.scss
Labels: bug

#70 fix/#69 - Add src, test and demo to .npmignore in generator
  generator/generator-opc-generator/generators/app/templates/_.npmignore
Labels: chore

#71 fix(#58) - Adding main to generator package.json and bump version for generator
  generator/generator-opc-generator/generators/app/templates/package.json
  generator/generator-opc-generator/package.json
Labels: chore

#97 Adds support for accessibility test.
  generator/generator-opc-generator/generators/app/templates/package.json
  generator/generator-opc-generator/generators/app/templates/test/_test.ts
Labels: enhancement
