Repository 1-Platform/op-components, pull requests merged in 2020-08, with the labels that each got.

#10 fix(#6) - Changes for generator README.md and other fixes
  .github/PULL_REQUEST_TEMPLATE.md
  generator/generator-opc-generator/README.md
  generator/generator-opc-generator/generators/app/index.js
  generator/generator-opc-generator/generators/app/templates/_.gitignore
  generator/generator-opc-generator/package-lock.json
  generator/generator-opc-generator/package.json
Labels: enhancement

#18 fix(#17) - Add latest browser support for Chrome and firefox in the PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: chore

#21 fix(#20) - Add the dist folder to .gitignore and Add storybook.js and the demo folder
  generator/generator-opc-generator/__tests__/app.js
  generator/generator-opc-generator/generators/app/templates/_.gitignore
  generator/generator-opc-generator/generators/app/templates/demo/index.html
  generator/generator-opc-generator/generators/app/templates/package.json
  generator/generator-opc-generator/generators/app/templates/webpack.config.js
Labels: enhancement

#23 Addes the public config to package.json file and updated the @import line in README.md file
  packages/opc-styles/README.md
  packages/opc-styles/package.json
Labels: chore

#25 fix(#24) - Bump up the version for generator
  generator/generator-opc-generator/package-lock.json
  generator/generator-opc-generator/package.json
Labels: chore, dependencies

#26 fix: Using pull_request_target instead of pull_request to fix forked repo actions
  .github/workflows/notify.yml
Labels: chore

#28 fix: Re-enable notification for prs from main repo branches
  .github/workflows/notify-fork.yml
  .github/workflows/notify-main.yml
Labels: chore

#36 fix: fixed github actions syntax
  .github/workflows/notify-fork.yml
  .github/workflows/notify-main.yml
Labels: chore

#32 Added the Gap and Space variables for the opc-styles.
  packages/opc-styles/README.md
  packages/opc-styles/package.json
  packages/opc-styles/typography/_base.scss
  packages/opc-styles/variables/_1-definitions.scss
Labels: chore
