Repository 1-Platform/op-components, pull requests merged in 2021-09, with the labels that each got.

#386 Added flat attribute to remove cube illustration.
  packages/opc-footer/README.md
  packages/opc-footer/demo/index.html
  packages/opc-footer/package-lock.json
  packages/opc-footer/package.json
  packages/opc-footer/src/opc-footer.scss
  packages/opc-footer/src/opc-footer.ts
Labels: enhancement

#387 feat(1488): opc-feedback removed transparency and zIndex reduced
  packages/opc-feedback/package.json
  packages/opc-feedback/src/assets.ts
  packages/opc-feedback/src/opc-feedback.scss
  packages/opc-feedback/src/opc-feedback.ts
Labels: enhancement

#371 fix(storybook-build-deploy) - Add storybook deploy on merge
  .github/workflows/storybook-build-deploy.yml
Labels: chore

#389 fix(storybook-deploy-hotfix) - Fix for multiple run requests
  .github/workflows/storybook-build-deploy.yml
Labels: bug

#391 fix(storybook-hotfix) - Storybook deploy workflow
  .github/workflows/storybook-build-deploy.yml
Labels: bug

#388 feat(1488): opc-nav position fixed to top in chrome
  packages/opc-nav/README.md
  packages/opc-nav/demo/index.html
  packages/opc-nav/package.json
  packages/opc-nav/src/opc-nav-search.scss
  packages/opc-nav/src/opc-nav.scss
  packages/opc-nav/src/opc-nav.ts
Labels: bug

#392 feat(1488): ui improvments and search on drawer components
  packages/opc-menu-drawer/README.md
  packages/opc-menu-drawer/declaration.d.ts
  packages/opc-menu-drawer/demo/index.html
  packages/opc-menu-drawer/demo/opc-menu-drawer.stories.js
  packages/opc-menu-drawer/docs/opc-menu-drawer-footer.png
  packages/opc-menu-drawer/docs/opc-menu-drawer-header-collapsed.png
  packages/opc-menu-drawer/docs/opc-menu-drawer-header-expanded.png
  packages/opc-menu-drawer/docs/opc-menu-drawer-links.png
  packages/opc-menu-drawer/package-lock.json
  packages/opc-menu-drawer/package.json
  packages/opc-menu-drawer/src/assets.ts
  packages/opc-menu-drawer/src/opc-menu-drawer-search.scss
  packages/opc-menu-drawer/src/opc-menu-drawer.scss
  packages/opc-menu-drawer/src/opc-menu-drawer.ts
  packages/opc-menu-drawer/test/opc-menu-drawer.test.ts
  packages/opc-notification-drawer/README.md
  packages/opc-notification-drawer/demo/index.html
  packages/opc-notification-drawer/docs/opc-notification-drawer.png
  packages/opc-notification-drawer/package-lock.json
  packages/opc-notification-drawer/package.json
  packages/opc-notification-drawer/src/opc-notification-drawer.scss
  packages/opc-notification-drawer/src/opc-notification-drawer.ts
  packages/opc-notification-drawer/test/opc-notification-drawer.test.ts
Labels: enhancement

#399 Update storybook-build-deploy.yml
  .github/workflows/storybook-build-deploy.yml
Labels: dependencies

#401 Update storybook-build-deploy.yml
  .github/workflows/storybook-build-deploy.yml
Labels: dependencies

#403 Update storybook-build-deploy.yml
  .github/workflows/storybook-build-deploy.yml
Labels: chore

#404 Update storybook-build-deploy.yml
  .github/workflows/storybook-build-deploy.yml
Labels: chore
