Repository 1-Platform/op-components, pull requests merged in 2021-02, with the labels that each got.

#202 fix(#201) - The timeline component doesn't render the horizontal line in the compact version
  packages/opc-timeline/package-lock.json
  packages/opc-timeline/package.json
  packages/opc-timeline/src/opc-timeline.scss
  packages/opc-timeline/src/opc-timeline.ts
Labels: bug

#190 feat(#838): opc-feedback component readiness
  README.md
  packages/opc-feedback/.npmignore
  packages/opc-feedback/LICENSE
  packages/opc-feedback/README.md
  packages/opc-feedback/assets/good.svg
  packages/opc-feedback/assets/happy.svg
  packages/opc-feedback/assets/sad.svg
  packages/opc-feedback/declaration.d.ts
  packages/opc-feedback/demo/index.html
  packages/opc-feedback/jest.config.js
  packages/opc-feedback/package-lock.json
  packages/opc-feedback/package.json
  packages/opc-feedback/src/defaultTemplate.ts
  packages/opc-feedback/src/opc-feedback.scss
  packages/opc-feedback/src/opc-feedback.ts
  packages/opc-feedback/test/opc-feedback.test.ts
  packages/opc-feedback/tsconfig.json
  packages/opc-feedback/webpack.config.js
Labels: enhancement

#213 chore:(1023) - Moved the assets to a variable and updated webpack config as default
  packages/opc-feedback/assets/good.svg
  packages/opc-feedback/assets/happy.svg
  packages/opc-feedback/assets/sad.svg
  packages/opc-feedback/package.json
  packages/opc-feedback/src/defaultTemplate.ts
  packages/opc-feedback/webpack.config.js
Labels: chore

#232 fix:(838) - Included the bug modal and a root template to feedback
  packages/opc-feedback/README.md
  packages/opc-feedback/declaration.d.ts
  packages/opc-feedback/demo/index.html
  packages/opc-feedback/package-lock.json
  packages/opc-feedback/package.json
  packages/opc-feedback/src/assets.ts
  packages/opc-feedback/src/defaultTemplate.ts
  packages/opc-feedback/src/opc-feedback.scss
  packages/opc-feedback/src/opc-feedback.ts
  packages/opc-feedback/test/opc-feedback.test.ts
Labels: chore, documentation
