Repository 1-Platform/op-components, pull requests merged in 2021-07, with the labels that each got.

#341 chore: updated the lit dependency.
  packages/opc-back-to-top/package-lock.json
  packages/opc-back-to-top/package.json
Labels: chore

#343 Dependency update for lit 2.0 for generator
  generator/generator-opc-generator/generators/app/templates/package.json
Labels: chore

#344 Dependency update lit 2.0 for opc-header
  packages/opc-header/package-lock.json
  packages/opc-header/package.json
Labels: chore

#345 Dependency update for lit 2.0 for input-chip
  packages/opc-input-chip/package-lock.json
  packages/opc-input-chip/package.json
Labels: chore

#346 Dependency update lit 2.0 for timeline
  packages/opc-timeline/package-lock.json
  packages/opc-timeline/package.json
Labels: chore

#353 Fix/#351 - Add test and build automation for all the components
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  generator/generator-opc-generator/generators/app/templates/package.json
  package-lock.json
  package.json
  packages/opc-back-to-top/package-lock.json
  packages/opc-back-to-top/package.json
  packages/opc-comment-input/package-lock.json
  packages/opc-comment-input/package.json
  packages/opc-feedback/package-lock.json
  packages/opc-feedback/package.json
  packages/opc-footer/package-lock.json
  packages/opc-footer/package.json
  packages/opc-header/package-lock.json
  packages/opc-header/package.json
  packages/opc-input-chip/package-lock.json
  packages/opc-input-chip/package.json
  packages/opc-styles/package.json
  packages/opc-timeline/package-lock.json
  packages/opc-timeline/package.json
Labels: chore, documentation, enhancement

#356 fix(#355) - Update the generator code
  generator/generator-opc-generator/generators/app/templates/src/_index.ts
Labels: chore

#352 Opc-Nav Component
  .editorconfig
  package-lock.json
  packages/opc-nav/.npmignore
  packages/opc-nav/LICENSE
  packages/opc-nav/README.md
  packages/opc-nav/declaration.d.ts
  packages/opc-nav/demo/index.html
  packages/opc-nav/demo/logo.svg
  packages/opc-nav/demo/opc-nav.stories.js
  packages/opc-nav/docs/opc-nav-custom-btn.png
  packages/opc-nav/docs/opc-nav-with-links.png
  packages/opc-nav/docs/opc-nav-with-logo.png
  packages/opc-nav/jest.config.js
  packages/opc-nav/package-lock.json
  packages/opc-nav/package.json
  packages/opc-nav/src/assets.ts
  packages/opc-nav/src/opc-nav.scss
  packages/opc-nav/src/opc-nav.ts
  packages/opc-nav/test/opc-nav.test.ts
  packages/opc-nav/tsconfig.json
  packages/opc-nav/webpack.config.js
Labels: enhancement

#357 Update package.json with concurrency set to 1
  package.json
Labels: chore

#354 opc-menu-drawer component
  packages/opc-menu-drawer/.npmignore
  packages/opc-menu-drawer/LICENSE
  packages/opc-menu-drawer/README.md
  packages/opc-menu-drawer/declaration.d.ts
  packages/opc-menu-drawer/demo/index.html
  packages/opc-menu-drawer/demo/opc-menu-drawer.stories.js
  packages/opc-menu-drawer/docs/opc-menu-drawer-footer.png
  packages/opc-menu-drawer/docs/opc-menu-drawer-header-collapsed.png
  packages/opc-menu-drawer/docs/opc-menu-drawer-header-expanded.png
  packages/opc-menu-drawer/docs/opc-menu-drawer-links.png
  packages/opc-menu-drawer/jest.config.js
  packages/opc-menu-drawer/package-lock.json
  packages/opc-menu-drawer/package.json
  packages/opc-menu-drawer/src/assets.ts
  packages/opc-menu-drawer/src/opc-menu-drawer.scss
  packages/opc-menu-drawer/src/opc-menu-drawer.ts
  packages/opc-menu-drawer/test/opc-menu-drawer.test.ts
  packages/opc-menu-drawer/tsconfig.json
  packages/opc-menu-drawer/webpack.config.js
Labels: enhancement
